version: "3.9"
services:
  backend:
    build: ./mod-checkup-backend
    container_name: backend
    ports:
      - 5000:5000
    env_file:
      - .env.production
  frontend:
    build: ./Final-Project-testapp
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend